spring.application.name=Seed2Stem

spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:28147/railway
spring.datasource.username=postgres
spring.datasource.password=ETjIEesOcgWBNHCJymDKzmvwxlhijGaE
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
server.port=5000

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/New_York

# SOP PDF upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB